name: s3_env
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libedit=3.1.20191231=he28a2e2_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - libiconv=1.18=h3b78370_2
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - ncurses=6.4=h6a678d5_0
  - openssl=3.5.4=h26f9b46_0
  - pip=25.0=py39h06a4308_0
  - pyodbc=5.2.0=py39hf88036b_0
  - python=3.9.21=he870216_1
  - python_abi=3.9=2_cp39
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - unixodbc=2.3.12=h661eb56_0
  - wheel=0.45.1=py39h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.3.1
      - asttokens==3.0.0
      - astunparse==1.6.3
      - boto3==1.38.1
      - botocore==1.38.1
      - certifi==2025.10.5
      - cffi==1.17.1
      - charset-normalizer==3.4.4
      - contourpy==1.3.0
      - cycler==0.12.1
      - decorator==5.2.1
      - et-xmlfile==2.0.0
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.14.0
      - idna==3.11
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - ipython==8.18.1
      - jedi==0.19.2
      - jmespath==1.0.1
      - keras==3.10.0
      - kiwisolver==1.4.7
      - libclang==18.1.1
      - llvmlite==0.43.0
      - markdown==3.9
      - markdown-it-py==3.0.0
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - mysql-connector-python==9.3.0
      - namex==0.1.0
      - narwhals==2.11.0
      - numba==0.60.0
      - numpy==1.26.4
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optree==0.17.0
      - packaging==25.0
      - paho-mqtt==2.1.0
      - pandas==2.2.3
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==11.3.0
      - plotly==6.4.0
      - prompt-toolkit==3.0.52
      - protobuf==6.33.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pydub==0.25.1
      - pyfilterbank @ git+https://github.com/SiggiGue/pyfilterbank.git@87b9bb52cb6ecdbcbc0385f1c10ed040b22b49d1
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2025.9.18
      - requests==2.32.5
      - resampy==0.4.3
      - rich==14.2.0
      - s3transfer==0.12.0
      - scipy==1.13.1
      - seaborn==0.13.2
      - six==1.17.0
      - soundfile==0.13.1
      - stack-data==0.6.3
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.1.0
      - tflite-runtime==2.14.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==1.26.20
      - wcwidth==0.2.14
      - werkzeug==3.1.3
      - wrapt==2.0.0
      - xlsx2csv==0.8.4
      - zipp==3.23.0
prefix: /home/aac_s3_test/miniconda3/envs/s3_env
